# Generated by Django 4.1.7 on 2023-06-13 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='书名')),
                ('author', models.CharField(max_length=50, verbose_name='作者')),
                ('published_date', models.DateField(verbose_name='入库时间')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='价格')),
                ('number', models.CharField(max_length=8, verbose_name='编号')),
            ],
        ),
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名字')),
                ('student_id', models.CharField(max_length=20, verbose_name='学号')),
                ('college', models.SmallIntegerField(choices=[(1, '电子学院'), (2, '艺术学院'), (3, '文化学院')], verbose_name='学院')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('username', models.CharField(max_length=12, verbose_name='账号')),
                ('password', models.CharField(max_length=12, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_date', models.DateField(verbose_name='借阅时间')),
                ('returned_date', models.DateField(blank=True, null=True, verbose_name='归还时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.book', verbose_name='书名')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.borrower', verbose_name='借阅人')),
            ],
        ),
    ]
