# Generated by Django 3.2.20 on 2023-07-26 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='student_id',
            field=models.CharField(max_length=8, verbose_name='学号'),
        ),
    ]
