# Generated by Django 3.2.20 on 2023-08-01 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_borrower_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='名称')),
                ('account', models.CharField(max_length=12, verbose_name='账号')),
                ('password', models.CharField(max_length=12, verbose_name='密码')),
            ],
        ),
    ]
