# Generated by Django 3.2.20 on 2023-08-01 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='account',
            new_name='username',
        ),
    ]
