# Generated by Django 3.2.20 on 2023-08-03 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_rename_account_admin_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='borrower_admin',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app1.admin', verbose_name='管理员借阅人'),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='borrower',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app1.borrower', verbose_name='借阅人'),
        ),
    ]
