# Generated by Django 3.2.20 on 2023-08-03 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20230803_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminBorrowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_date', models.DateField(verbose_name='借阅时间')),
                ('returned_date', models.DateField(blank=True, null=True, verbose_name='归还时间')),
            ],
        ),
        migrations.CreateModel(
            name='ComBorrowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_date', models.DateField(verbose_name='借阅时间')),
                ('returned_date', models.DateField(blank=True, null=True, verbose_name='归还时间')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='account',
            field=models.PositiveIntegerField(default=0, verbose_name='借阅次数'),
        ),
        migrations.DeleteModel(
            name='Borrowing',
        ),
        migrations.AddField(
            model_name='comborrowing',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.book', verbose_name='书名'),
        ),
        migrations.AddField(
            model_name='comborrowing',
            name='borrower',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app1.borrower', verbose_name='借阅人'),
        ),
        migrations.AddField(
            model_name='adminborrowing',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.book', verbose_name='书名'),
        ),
        migrations.AddField(
            model_name='adminborrowing',
            name='borrower',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app1.borrower', verbose_name='借阅人'),
        ),
    ]
